### ISSUE TITLE
|c_i| = 0

### ISSUE THREAD

**Issue by badmutex** [badmutex/ma-arafah#2]
Running for k = 50 on OS X gives |c_0| = 0 at the beginning of iteration 2 in step 1.

This may be a problem when step 2 begins.

**Comment by badmutex** [comment]
Exception in thread "main" java.util.NoSuchElementException
        at java.util.AbstractList$Itr.next(AbstractList.java:350)
        at tajmi.data.clusterable.cdk.AtomContainer_CenterOfMassAlgorithm.center(AtomContainer_CenterOfMassAlgorithm.java:27)
        at tajmi.data.clusterable.cdk.AtomContainer_CenterOfMassAlgorithm.center(AtomContainer_CenterOfMassAlgorithm.java:16)
        at tajmi.data.KMeans.step2(KMeans.java:267)
        at tajmi.data.KMeans.done(KMeans.java:92)
        at tajmi.data.KMeans.call(KMeans.java:72)
        at tajmi.Main.main(Main.java:76)
